### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/rank-my-wallet#75]
- https://blog.logrocket.com/complete-guide-internationalization-nextjs/
- https://lingui.js.org/
- https://lingui.dev/tutorials/react
- https://github.com/vercel/next.js/tree/canary/examples/with-lingui
- https://codesandbox.io/s/djzqm?file=/lingui-example/i18n.ts
- https://stackblitz.com/edit/github-qnfa4f

### Tasks

- [x] Next subpath routing
- [x] Lingui configuration
- [x] Lingui use `.po` files in development so file saves trigger a page refresh. Only use the `.js` files in production
- [x] npm run scripts
- [x] gitignore `*.mo` files as produced by e.g. Poedit
- [x] Use lingui `defineMessage()` for `src/core/constants` etc.
- [x] Fix imports, always use `loader`
- [x] Use [eslint plugin for lingui](https://www.npmjs.com/package/eslint-plugin-string-to-lingui) (to detect usage of macros outside components etc.)
- [x] Use Lingui `context` to differentiate between words that are identical in both singular and plural form
- [x] ~[Dialect fallback using `nonExplicitSupportedLngs`](https://github.com/i18next/next-i18next/pull/1930) for e.g. non-existing `nl-BE` translation to fallback to `nl`~ DROPPED to prevent catalog loading bloat.
- [x] Test Lingui duplicates (multiple use of single translation)
- [x] Plural support
- [x] Naming convention for `*.po` file `msgid`. **Conclusion:** do not use any, stick to natural language. Leads to a better translator experience, no double work and much cleaner code
- [x] Language dropdown:
  - Something [like this](https://codesandbox.io/s/chakra-ui-phone-input-i4l96)
  -  Dutch (nl)
  - Nederlands (nl)
  - Nederlands (be)
  - オランダの (nl)
  - (nl) هولندي
  - 擬似 (pseudo), dev-only
  - [x] country flag icon using [react-country-flag](https://github.com/danalloway/react-country-flag) derived from Lingui active locale
  - [x] Sort dropdown alphabetically
  - [x] Pseudo available in dev-mode only
  - [x] Dropdown translations
  - [x] Add terrritory to dropdown (when applicabale)
- [x] No assumptions: 
  - [x] Names like カルダノfor Cardano
- [x] Replace `capitalize()` with capitalization in the `.po` files because of [languages without capital letters](https://www.quora.com/Which-languages-have-no-capitalized-letter) etc.
- [x] `lang` meta tag
- [x] Sitemap: #105
- [x] Husky pre-commit hook should prevent file diffs between `npm run translations:extract` and e.g. Poedit. **Update:** not required when using crowdin
- [x] About: technology stack
- [x]  Readme: 
  - [x] [Poedit](https://poedit.net/)
  - [x] Updates vs new language
  - [x] New languange: update `next.config.js`, `src/translations/setup.ts`
- [x] FAQ:
  - [x] How do I add a translation?
- [ ] Extend `bigToString.test.ts` with other locales
- [ ] Localized numbers
  - [x] indian separators
  - [ ] ar-EG
  - [ ] [Japanese](https://www.learnjapanesetools.com/nl/numbers-to-japanese-numbers)?
- [x] Support Indian numbering for Counter component
- [x] Consider https://crowdin.com/ 
### Good to know:

- Language in `NEXT_LOCALE` cookie wins over `ACCEPT_LANGUAGE` header
- Language in `ACCEPT_LANGUAGE` supported: **route to language**. Not supported: fall back to default language.
- Only use Lingui macros. They transform code before parsing to Babel and lead to cleaner code.

### Poedit

Disable below POEdit setting to prevent creation of `*.mo` files:

![image](https://user-images.githubusercontent.com/230500/219130827-39c76e2a-d7de-427e-947a-2fb09e118bbe.png)
